### ISSUE TITLE
start command gives spawn ./ngrok ENOENT: Error 

### ISSUE THREAD

**Issue by bsonmez** [philnash/ngrok-for-vscode#24]
I use the latest version of ngrok-for-vscode as well as vscode itself.

Since yesterday from a sudden, the start command doesn't work. When I checked the logs, it gives the error below.

```
[2021-03-09 20:33:07.840] [renderer1] [error] spawn ./ngrok ENOENT: Error: spawn ./ngrok ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2021-03-09 20:35:43.610] [renderer1] [error] spawn ./ngrok ENOENT: Error: spawn ./ngrok ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2021-03-09 20:46:12.124] [renderer1] [error] spawn ./ngrok ENOENT: Error: spawn ./ngrok ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2021-03-09 20:46:29.777] [renderer1] [error] spawn ./ngrok ENOENT: Error: spawn ./ngrok ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2021-03-09 20:46:38.233] [renderer1] [error] spawn ./ngrok ENOENT: Error: spawn ./ngrok ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2021-03-09 20:46:56.419] [renderer1] [error] spawn ./ngrok ENOENT: Error: spawn ./ngrok ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2021-03-09 20:46:59.781] [renderer1] [error] spawn ./ngrok ENOENT: Error: spawn ./ngrok ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2021-03-09 20:47:05.254] [renderer1] [error] spawn ./ngrok ENOENT: Error: spawn ./ngrok ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2021-03-09 20:47:22.414] [renderer1] [error] spawn ./ngrok ENOENT: Error: spawn ./ngrok ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2021-03-09 20:52:30.461] [renderer1] [error] spawn ./ngrok ENOENT: Error: spawn ./ngrok ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2021-03-09 20:52:35.216] [renderer1] [error] spawn ./ngrok ENOENT: Error: spawn ./ngrok ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)

```

**Comment by philnash** [comment]
This is weird, as I'm also getting this myself. Will look into it as soon as I can.

**Comment by bsonmez** [comment]
> This is weird, as I'm also getting this myself. Will look into it as soon as I can.

Yes! Super weird. I cleaned VSCode caches, downgrade the version of ngrok-for-vscode, reinstalled, and none of them did not work.

**Comment by eladmeidar** [comment]
Same here - nothing much to add but it seems to be around the way `spawn` is used. could be related to local Node.js version?

**Comment by philnash** [comment]
I thought it might be something to do with the way `spawn` was called in the `ngrok` package, and initially changing `./ngrok` to `ngrok` fixed things. But that was only because it was then calling on my globally installed `ngrok` executable, not the one provided by the `ngrok` Node package. So that was a dead end.

It appears that the ngrok executable that is downloaded is present, which makes no sense as it then can't find it (`ENOENT`).

I wonder if this has anything to do with `npm` upgrades and how processes are run postinstall.

Other than that, I'm a bit lost right now.

**Comment by bsonmez** [comment]
It's really super weird. I really don't want to mix things up, but I have another MacBook with the same environment as I currently use (node versions, VS code versions, etc.) It doesn't have such an issue. So I'm not sure if it is related with node.

**Comment by bsonmez** [comment]
> It's really super weird. I really don't want to mix things up, but I have another MacBook with the same environment as I currently use (node versions, VS code versions, etc.) It doesn't have such an issue. So I'm not sure if it is related with node.

I recently noticed that my second Macbook started having the issue. Then, realized the vscode updated. So I guess it is a vscode related issue.

**Comment by philnash** [comment]
Thanks for the update, at least we're finding a reason for consistency and I have somewhere to look. Hope to sort this soon!

**Comment by philnash** [comment]
Ok, turns out this was a problem upstream in [ngrok](https://github.com/bubenshchykov/ngrok/pull/216) which I have fixed.

Update ngrok-for-vscode to version 1.8.4 and it should work again.

**Comment by bsonmez** [comment]
> Ok, turns out this was a problem upstream in [ngrok](https://github.com/bubenshchykov/ngrok/pull/216) which I have fixed.
> 
> Update ngrok-for-vscode to version 1.8.4 and it should work again.

Thank you, Phil!
