### ISSUE TITLE
Ngrok binary won't download

### ISSUE THREAD

**Issue by synth** [philnash/ngrok-for-vscode#27]
Hello, 

Thanks for this extension. After activating this extension and restarting VSCode, I get the error: 

> Can't update ngrok binary. The extension may not work correctly.

Upon further inspection, in the debug logs, I get: 

<img width="1024" alt="Screen Shot 2021-09-10 at 6 29 42 PM" src="https://user-images.githubusercontent.com/10546/132931992-f81f56a8-0661-48c2-a1db-7bc0b245f0fd.png">

When I `ll` into the extension directory, I notice that the `bin` directory is missing. If I manually create this directory after installation, but before doing a `ngrok start` command (which kicks off the binary download), and THEN do `ngrok start`, it works!

Not sure why the `bin` directory is missing upon installation.

**Comment by philnash** [comment]
Hey @synth, thanks for the report and sorry that it's currently broken. I have recently updated the ngrok dependency, so that might fix things. I'll see what I can do to release a new version that should work as soon as possible.

**Comment by synth** [comment]
No problem, thanks!

**Comment by christopher-read** [comment]
Hi, 
Just got the same error:

This was in the Log (Window)
`
2021-12-23 11:56:08.847] [renderer1] [error] [Extension Host] (node:25780) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
[2021-12-23 11:56:10.722] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2021-12-23 11:56:48.682] [renderer1] [error] [Extension Host] ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip
[2021-12-23 11:56:49.134] [renderer1] [error] [Extension Host] 
ngrok - error downloading from URL RequestError: certificate has expired
    at ClientRequest.<anonymous> (c:\Users\chris\.vscode\extensions\philnash.ngrok-for-vscode-1.9.1\dist\extension.js:2:72009)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.e.emit (c:\Users\chris\.vscode\extensions\philnash.ngrok-for-vscode-1.9.1\dist\extension.js:2:10510)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
.
.
.
2021-12-23 12:10:45.747] [renderer1] [warning] Settings pattern "keyboard.*" doesn't match any settings
[2021-12-23 12:15:17.612] [renderer1] [warning] Settings pattern "keyboard.*" doesn't match any settings
[2021-12-23 12:17:09.233] [renderer1] [error] spawn c:\Users\chris\.vscode\extensions\philnash.ngrok-for-vscode-1.9.1\dist\bin\ngrok.exe ENOENT: Error: spawn c:\Users\chris\.vscode\extensions\philnash.ngrok-for-vscode-1.9.1\dist\bin\ngrok.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
`


as a workaround, I copied my ngrok.exe to the extension's bin folder:
c:\Users\chris\.vscode\extensions\philnash.ngrok-for-vscode-1.9.1\dist\bin\ngrok.exe

**Comment by asherbig** [comment]
I also ran into the same issue as @christopher-read and his solution fixed it

**Comment by philnash** [comment]
I've just updated the ngrok dependency again. If you are still getting this problem, could you try updating to 1.9.2 and running it again? Thanks!
