### ISSUE TITLE
Support for ngrok agent configuration file v3

### ISSUE THREAD

**Issue by dr-impossible** [philnash/ngrok-for-vscode#63]
ngrok has introduced a new config file version, v3. When you upgrade to this new format using the command `ngrok config upgrade`, starting a tunnel with ngrok for VSCode fails with the following error message:

```
2024-12-05 14:02:12.499 [error] [Extension Host] TypeError: Cannot read properties of undefined (reading 'body')
	at NgrokClient.request (~/.vscode/extensions/philnash.ngrok-for-vscode-1.10.1/dist/extension.js:1:135246)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async m (~/.vscode/extensions/philnash.ngrok-for-vscode-1.10.1/dist/extension.js:1:134075)
```
(home path redacted with `~`)

I'm using 
ngrok for VSCode v1.10.1
Visual Studio Code 1.95.3
ngrok cli version 3.18.4

the `ngrok config upgrade` command creates a backup of your old config and prints the location in its output

**Comment by philnash** [comment]
Yeah, I am aware of that and I just got stalled in updating the underlying ngrok package that powers this.

Meanwhile, however, I have a branch that uses ngrok's own provided JavaScript library to power this extension. That will decouple it from the CLI tool and avoid issues like this. I'm just a build process (for multiple platforms) away from releasing.
